# Site settings
title: 拾遗
email: cairen98@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.gl6.cc" # the base hostname & protocol for your site


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'


# Social account
twitter:  h3l10wor1d
weibo:    WhyJustMe
github:   ctwj
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
google_analytics: UA-77807415-1


# Build settings
highlighter: pygments
markdown: kramdown
redcarpet:
extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
sass:
  style: compressed
gems:
  - jekyll-sitemap
